<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERMS.Contracts\ERMS.Contracts.csproj" />
    <ProjectReference Include="..\ERMS.Domain\ERMS.Domain.csproj" />
    <ProjectReference Include="..\ERMS.SharedKernel\ERMS.SharedKernel.csproj" />
	<PackageReference Include="MediatR" /> 
	<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" /> 
	<PackageReference Include="FluentValidation" /> 
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
